---
title: "Predicting insurance purchase for Indian farmers"
graphics: yes
output:
  pdf_document:
    toc: yes
    toc_depth: '4'
  word_document:
    toc: yes
    toc_depth: '4'
  html_document:
    code_folding: show
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
subtitle: STAT 471/571/701, Fall 2018
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot[CO,CE]{}
- \fancyfoot[LE,RO]{\thepage}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      tidy = TRUE, fig.width = 7, fig.height = 4,
                      fig.align='left', dev = 'pdf')
if(!require("pacman")) install.packages("pacman")
if(!require("pROC")) install.packages("pROC")
pacman::p_load(dplyr, ggplot2, glmnet, car, corrplot)
library(pROC)
library(devtools)
```



# Introduction

## Background


## Goal of the study


## The data



### Characteristics of the Data Set


### Description of variables


# Research approach


## Analyses of dataset


```{r}
# Import data and split into train vs. test
# rm(list = ls())
caravan_kaggle<- read.csv("caravan-insurance-challenge.csv", header = T)
caravan.train <- caravan_kaggle[caravan_kaggle$ORIGIN %in% "train",]
caravan.train <- caravan.train[-1] #delete "ORIGIN" column
caravan.test <- caravan_kaggle[caravan_kaggle$ORIGIN %in% "test",]
caravan.test <- caravan.test[-1] #delete "ORIGIN" column
summary(caravan.train)
```

```{r}
# Create full logistic regression model
fit.logit.0 <- glm(CARAVAN~., family=binomial, data=caravan.train)
summary(fit.logit.0)

# Get ROC and AUC
prob=predict(fit.logit.0,type=c("response"))
caravan.train$prob=prob
library(pROC)
g <- roc(CARAVAN ~ prob, data = caravan.train)
g
plot(g)

# Incorporate loss of 0.2 since we are much more comfortable marketing to those who are less likely to purchase than missing people who may have bought insurance
fit.pred.2 <- rep("0", 5822)
fit.pred.2[fit.logit.0$fitted > .2] <- "1"

# Find MCE
MCE.2 <- (sum(5*(fit.pred.2[caravan.train$CARAVAN == "1"] != "1")) + sum(fit.pred.2[caravan.train$CARAVAN == "0"] != "0"))/length(caravan.train$CARAVAN)
MCE.2
```

```{r}
# Logistic with backward selection
caravan.train <- caravan.train[-87] #delete "prob" column
fit.backward <- regsubsets(CARAVAN ~., caravan.train, nvmax=8, method="backward")
f.b <- summary(fit.backward)
f.b

plot(f.b$cp,  col="red", type="p", pch=16,
   xlab="Backward Selection")

coef(fit.backward, 8)

# Fit glm model
fit.logit.1 <- glm(CARAVAN~MRELGE+MOPLLAAG+MBERBOER+PWALAND+PPERSAUT+PBRAND+APLEZIER+ABYSTAND, family=binomial, data=caravan.train)

# Get ROC and AUC
prob=predict(fit.logit.1,type=c("response"))
caravan.train$prob=prob
g <- roc(CARAVAN ~ prob, data = caravan.train)
g
plot(g)

# Incorporate loss of 0.2 since we are much more comfortable marketing to those who are less likely to purchase than missing people who may have bought insurance
fit.pred.2 <- rep("0", 5822)
fit.pred.2[fit.logit.1$fitted > .2] <- "1"

# Find MCE
MCE.2 <- (sum(5*(fit.pred.2[caravan.train$CARAVAN == "1"] != "1")) + sum(fit.pred.2[caravan.train$CARAVAN == "0"] != "0"))/length(caravan.train$CARAVAN)
MCE.2
```

```{r}
# LASSO technique and elastic net
# First, we prepare the design matrix and response
X <- model.matrix(CARAVAN~., caravan.train)[,-1]
Y <- caravan.train[, 86]

set.seed(10) # to have same sets of K folds
fit2.cv <- cv.glmnet(X, Y, alpha=1, family="binomial", nfolds = 10, type.measure = "deviance")  
plot(fit2.cv)
coef.min <-coef(fit2.cv, s="lambda.min") 
coef.min <- coef.min[which(coef.min !=0), ]
as.matrix(coef.min)

# Next, we use glm() with the variables obtained from LASSO above
beta.min <- rownames(as.matrix(coef.min))
beta.min

# Create the logistic regression summary
fit.logit.2 <- glm(CARAVAN~MGEMLEEF+MGODRK+MGODPR+MGODGE+MRELGE+MRELSA+MOPLHOOG+MOPLLAAG+MBERBOER+MBERMIDD+MSKD+MHHUUR+MAUT1+MINKM30+MINK7512+MINK123M+MINKGEM+MKOOPKLA+PWAPART+PWALAND+PPERSAUT+PWERKT+PGEZONG+PWAOREG+PBRAND+PFIETS+ATRACTOR+AZEILPL+APLEZIER+AFIETS+ABYSTAND, family=binomial, data=caravan.train)
summary(fit.logit.2)

# Get ROC and AUC
prob=predict(fit.logit.2,type=c("response"))
caravan.train$prob=prob
g <- roc(CARAVAN ~ prob, data = caravan.train)
g
plot(g)

# Incorporate loss of 0.2 since we are much more comfortable marketing to those who are less likely to purchase than missing people who may have bought insurance
fit.pred.2 <- rep("0", 5822)
fit.pred.2[fit.logit.2$fitted > .2] <- "1"

# Find MCE
MCE.2 <- (sum(5*(fit.pred.2[caravan.train$CARAVAN == "1"] != "1")) + sum(fit.pred.2[caravan.train$CARAVAN == "0"] != "0"))/length(caravan.train$CARAVAN)
MCE.2
```