---
title: "Predicting insurance purchase for Indian farmers"
graphics: yes
output:
  html_document:
    code_folding: show
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '4'
  pdf_document:
    toc: yes
    toc_depth: '4'
subtitle: STAT 471/571/701, Fall 2018
header-includes:
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot[CO,CE]{}
- \fancyfoot[LE,RO]{\thepage}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      tidy = TRUE, fig.width = 7, fig.height = 4,
                      fig.align='left', dev = 'pdf')
if(!require("pacman")) install.packages("pacman")
if(!require("pROC")) install.packages("pROC")
pacman::p_load(dplyr, ggplot2, glmnet, car, corrplot)
library(pROC)
library(devtools)
library(rpart)
library(ranger)
library(randomForest)
library(tree)
```
```{r}
caravan_kaggle<- read.csv("caravan-insurance-challenge.csv", header = T)
```
```{r}
summary(caravan_kaggle)
```
```{r}
str(caravan_kaggle)
```
```{r}
#refactoring
caravan_kaggle$MOSTYPE <- factor(caravan_kaggle$MOSTYPE,
                              levels=c(1:41),
                              labels=c("High Income, expensive child",
                                       "Very Important Provincials",
                                       "High status seniors",
                                       "Affluent senior apartments",
                                       "Mixed seniors",
                                       "Career and childcare",
                                       "Dinki's (Double income no kids)",
                                       "Middle class families",
                                       "Modern, complete families",
                                       "Stable family","Family starters",
                                       "Affluent young families",
                                       "Young all american family",
                                       "Junior cosmopolitans",
                                       "Senior cosmopolitans",
                                       "Students in apartments",
                                       "Fresh masters in the city",
                                       "Single youth",
                                       "Suburban youth",
                                       "Ethnically diverse",
                                       "Young urban have-nots",
                                       "Mixed apartment dwellers",
                                       "Young and rising", 
                                       "Young, low educated", 
                                       "Yound seniros in the city",
                                       "Own home elderly",
                                       "Seniors in apartments",
                                       "Residential elderly",
                                       "Porchless seniors: no front yard",
                                       "Religious elderly singles",
                                       "Low income catholics",
                                       "Mixed seniors2",
                                       "Lower class large families",
                                       "Large family,employed child",
                                       "Village families",
                                       "Couples with teens 'Married with children'",
                                       "Mixed small town dwellers",
                                       "Traditional families",
                                       "Large religous families",
                                       "Large family farms",
                                       "Mixed rurals"))

#Average Age Refactor
caravan_kaggle$MGEMLEEF <- factor(caravan_kaggle$MGEMLEEF,
                     levels=c(1:6),
                     labels=c("20-30 years",
                              "30-40 years",
                              "40-50 years",
                              "50-60 years",
                              "60-70 years",
                              "70-80 years")) 

#Custom Main Type Refactor
caravan_kaggle$MOSHOOFD <- factor(caravan_kaggle$MOSHOOFD,
                                levels=(1:10),
                                labels=c("Successful hedonists",
                                         "Driven Growers",
                                         "Average Family",
                                         "Career Loners",
                                         "Living well",
                                         "Cruising Seniors",
                                         "Retired and Religious",
                                         "Family with grown ups",
                                         "Conservatie Families",
                                         "Farmers"))
```
```{r}
#Percentages Refactor
for (i in which(colnames(caravan_kaggle)=="MGODRK"):which(colnames(caravan_kaggle)=="MKOOPKLA")){
  caravan_kaggle[,i] <- factor(caravan_kaggle[,i],
                   levels=c(0:9),
                   labels=c("0%",
                            "1-10%",
                            "11-23%",
                            "24-36%",
                            "37-49%",
                            "50-62%",
                            "63-75%",
                            "76-88%",
                            "89-99%",
                            "100%"))
}
```
```{r}
#Number of Refactor
for (i in which(colnames(caravan_kaggle)=="PWAPART"):which(colnames(caravan_kaggle)=="ABYSTAND")){
  caravan_kaggle[,i] <- factor(caravan_kaggle[,i],
                   levels=c(0:9),
                   labels=c("0",
                            "1-49",
                            "50-99",
                            "100-199",
                            "200-499",
                            "500-999",
                            "1000-4999",
                            "5000-9999",
                            "10,000-19,999",
                            ">=20,000"))
}

#Set class label as factor 
caravan_kaggle$CARAVAN <- factor(caravan_kaggle$CARAVAN,levels=c("0","1"))
```
```{r}
#Remove NA's
caravan_kaggle<-caravan_kaggle[complete.cases(caravan_kaggle),]
```
```{r}
#Remove ORIGIN
caravan_kaggle<-caravan_kaggle[,-1]
```
```{r}
#Splitting into training and testing data
set.seed(123)
n <- nrow(caravan_kaggle)
n1 <- (2/3)*n
train_index <- sample(n, n1, replace=FALSE)
length(train_index)
ctrain <- caravan_kaggle[train_index, ]
ctest <- caravan_kaggle[-train_index, ]
dim(ctrain)
dim(ctest)
```

```{r}
# Create full logistic regression model
fit.logit.0 <- glm(CARAVAN~., family=binomial, data=ctrain)
summary(fit.logit.0)

# Get ROC and AUC
prob=predict(fit.logit.0,type=c("response"))
ctrain$prob=prob
library(pROC)
g <- roc(CARAVAN ~ prob, data = ctrain)
g
plot(g)

# Incorporate loss of 0.2 since we are much more comfortable marketing to those who are less likely to purchase than missing people who may have bought insurance
fit.pred.2 <- rep("0", 5822)
fit.pred.2[fit.logit.0$fitted > .2] <- "1"

# Find MCE
MCE.2 <- (sum(5*(fit.pred.2[ctrain$CARAVAN == "1"] != "1")) + sum(fit.pred.2[ctrain$CARAVAN == "0"] != "0"))/length(ctrain$CARAVAN)
MCE.2
```

```{r}
# Logistic with backward selection
ctrain <- ctrain[-87] #delete "prob" column
fit.backward <- regsubsets(CARAVAN ~., ctrain, nvmax=8, method="backward")
f.b <- summary(fit.backward)
f.b

plot(f.b$cp,  col="red", type="p", pch=16,
   xlab="Backward Selection")

coef(fit.backward, 8)

# Fit glm model
fit.logit.1 <- glm(CARAVAN~MRELGE+MOPLLAAG+MBERBOER+PWALAND+PPERSAUT+PBRAND+APLEZIER+ABYSTAND, family=binomial, data=ctrain)

# Get ROC and AUC
prob=predict(fit.logit.1,type=c("response"))
ctrain$prob=prob
g <- roc(CARAVAN ~ prob, data = ctrain)
g
plot(g)

# Incorporate loss of 0.2 since we are much more comfortable marketing to those who are less likely to purchase than missing people who may have bought insurance
fit.pred.2 <- rep("0", 5822)
fit.pred.2[fit.logit.1$fitted > .2] <- "1"

# Find MCE
MCE.2 <- (sum(5*(fit.pred.2[ctrain$CARAVAN == "1"] != "1")) + sum(fit.pred.2[ctrain$CARAVAN == "0"] != "0"))/length(ctrain$CARAVAN)
MCE.2
```

```{r}
# LASSO technique and elastic net
# First, we prepare the design matrix and response
X <- model.matrix(CARAVAN~., ctrain)[,-1]
Y <- ctrain[, 86]

set.seed(10) # to have same sets of K folds
fit2.cv <- cv.glmnet(X, Y, alpha=1, family="binomial", nfolds = 10, type.measure = "deviance")  
plot(fit2.cv)
coef.min <-coef(fit2.cv, s="lambda.min") 
coef.min <- coef.min[which(coef.min !=0), ]
as.matrix(coef.min)

# Next, we use glm() with the variables obtained from LASSO above
beta.min <- rownames(as.matrix(coef.min))
beta.min

# Create the logistic regression summary
fit.logit.2 <- glm(CARAVAN~MGEMLEEF+MGODRK+MGODPR+MGODGE+MRELGE+MRELSA+MOPLHOOG+MOPLLAAG+MBERBOER+MBERMIDD+MSKD+MHHUUR+MAUT1+MINKM30+MINK7512+MINK123M+MINKGEM+MKOOPKLA+PWAPART+PWALAND+PPERSAUT+PWERKT+PGEZONG+PWAOREG+PBRAND+PFIETS+ATRACTOR+AZEILPL+APLEZIER+AFIETS+ABYSTAND, family=binomial, data=ctrain)
summary(fit.logit.2)

# Get ROC and AUC
prob=predict(fit.logit.2,type=c("response"))
ctrain$prob=prob
g <- roc(CARAVAN ~ prob, data = ctrain)
g
plot(g)

# Incorporate loss of 0.2 since we are much more comfortable marketing to those who are less likely to purchase than missing people who may have bought insurance
fit.pred.2 <- rep("0", 5822)
fit.pred.2[fit.logit.2$fitted > .2] <- "1"

# Find MCE
MCE.2 <- (sum(5*(fit.pred.2[ctrain$CARAVAN == "1"] != "1")) + sum(fit.pred.2[ctrain$CARAVAN == "0"] != "0"))/length(ctrain$CARAVAN)
MCE.2
```

```{r}
#Building model on training data using randomForest package
rf.train <- randomForest(CARAVAN~., ctrain) 
plot(rf.train) #plotting the error vs number of trees to find optimal forest size
```
```{r}
predict.rf.yvar <- predict(rf.train, newdata=ctest)   
predict.rf.prob <- predict(rf.train, newdata=ctest, type="prob")  #predicting probabilities for ROC curve
#Testing errors
mean(ctest$CARAVAN != predict.rf.yvar) 
roc(ctest$CARAVAN, predict.rf.prob[,2], plot=TRUE)
```

```{r}
#Using ranger package since randomForest uses "majority vote" to grow the trees instead of offering customizability on Loss Function
#Running on overall data to find out OOB Error
library(ranger)
rf.ranger <- ranger(CARAVAN~., caravan_kaggle, mtry = 9, 
                    num.trees = 500, splitrule = "gini", importance = "impurity")
rf.ranger$prediction.error ##OOB Error
```
```{r}
#Using Test data for finding MCE/Testing Error
rf.ranger.mce <- ranger(CARAVAN~., ctrain, mtry = 9, 
                    num.trees = 500, splitrule = "gini", importance = "impurity")
rf.range.pred.mce <- predict(rf.ranger.mce, ctest, type = "response")
mean(ctest$CARAVAN != rf.range.pred.mce$predictions) ##Testing error
```
```{r}
#ROC Curve and AUC
rf.ranger.ROC <- ranger(CARAVAN~., ctrain, mtry = 9, 
                    num.trees = 500, splitrule = "gini", importance = "impurity", probability = T)
rf.ranger.pred.ROC <- predict(rf.ranger.ROC, ctest)$predictions[,1]
roc(ctest$CARAVAN, rf.ranger.pred.ROC, plot=TRUE)
```
```{r}
#Bayes Rule - Loss Function of 0.2
rf.test <- predict(rf.ranger.ROC, ctest)
rf.test.pred <- ifelse(rf.test$predictions[,2]<0.2,"0","1") #classifying probabilities less than 0.2 as 0, and rest as 1 
mean(ctest$CARAVAN != rf.test.pred) #MCE in testing data = Testing Error with loss function of 0.2
```
